AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  YetiTransactionsTableName:
    Description: The name of the main transactions table
    Type: String
  YetiLoginsTableName:
    Description: The name of the logins information table
    Type: String
  YetiTokensTableName:
    Description: The name of the token information table
    Type: String

Resources:
  YetiApiLoadTransactions:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: YetiApi-LoadTransactions
      Handler: yeti_api.load_transactions
      Timeout: 10
      Runtime: python3.6
      Events:
        LoadTransactions:
          Type: Api
          Properties:
            Path: /transactions
            Method: get
            RestApiId:
              Ref: ProjectYetiApi
      Policies:
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          YETI_TRANSACTIONS_TABLE:
            Ref: YetiTransactionsTableName
  YetiApiOutlookOAuth:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: YetiApi-OutlookOAuth
      Handler: yeti_api.login_outlook_oauth
      Timeout: 10
      Runtime: python3.6
      Events:
        OutlookOAuthLogin:
          Type: Api
          Properties:
            Path: /user/login/outlook_oauth
            Method: post
            RestApiId:
              Ref: ProjectYetiApi
      Policies:
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          YETI_TRANSACTIONS_TABLE:
            Ref: YetiTransactionsTableName
          YETI_LOGINS_TABLE:
            Ref: YetiLoginsTableName
          YETI_TOKENS_TABLE:
            Ref: YetiTokensTableName
  YetiApiLogin:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: YetiApi-Login
      Handler: yeti_api.login
      Timeout: 10
      Runtime: python3.6
      Events:
        Login:
          Type: Api
          Properties:
            Path: /user/login
            Method: post
            RestApiId:
              Ref: ProjectYetiApi
      Policies:
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          YETI_TRANSACTIONS_TABLE:
            Ref: YetiTransactionsTableName
          YETI_LOGINS_TABLE:
            Ref: YetiLoginsTableName
          YETI_TOKENS_TABLE:
            Ref: YetiTokensTableName

  YetiTransactionsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName:
        Ref: YetiTransactionsTableName
      AttributeDefinitions:
        - AttributeName: "TransactionId"
          AttributeType: "S"
        - AttributeName: "SenderFirstName"
          AttributeType: "S"
        - AttributeName: "SenderLastName"
          AttributeType: "S"
        - AttributeName: "SenderEmail"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "TransactionId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      GlobalSecondaryIndexes:
        - IndexName: "TransactionsBySenderNameIndex"
          KeySchema:
            - AttributeName: "SenderFirstName"
              KeyType: "HASH"
            - AttributeName: "SenderLastName"
              KeyType: "RANGE"
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: "3"
            WriteCapacityUnits: "3"
        - IndexName: "TransactionsBySenderEmailIndex"
          KeySchema:
            - AttributeName: "SenderEmail"
              KeyType: "HASH"
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: "3"
            WriteCapacityUnits: "3"
  YetiLoginsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName:
        Ref: YetiLoginsTableName
      AttributeDefinitions:
        - AttributeName: "Email"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "Email"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
  YetiTokensTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName:
        Ref: YetiTokensTableName
      AttributeDefinitions:
        - AttributeName: "AccessToken"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "AccessToken"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  # API Gateway
  ProjectYetiApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: ProjecYetiApi
      StageName: prod
      DefinitionUri: swagger.yml
