AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  YetiTransactionsTableName:
    Description: The name of the main transactions table
    Type: String

Resources:
  YetiApiLoadTransactions:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: YetiApi-LoadTransactions
      Handler: src/yeti_api.load_transactions
      Timeout: 10
      Runtime: python3.6
      Events:
        LoadTransactions:
          Type: Api
          Properties:
            Path: /transactions
            Method: get
      Policies:
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          YETI_TRANSACTIONS_TABLE:
            Ref: YetiTransactionsTableName
  YetiApiSearchTransactions:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: YetiApi-SearchTransactions
      Handler: src/yeti_api.search_transactions
      Timeout: 10
      Runtime: python3.6
      Events:
        SearchTransactions:
          Type: Api
          Properties:
            Path: /transactions/search
            Method: post
      Policies:
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          YETI_TRANSACTIONS_TABLE:
            Ref: YetiTransactionsTableName
  YetiApiCloseTransaction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: YetiApi-CloseTransaction
      Handler: src/yeti_api.close_transaction
      Timeout: 10
      Runtime: python3.6
      Events:
        LoadAllTransactions:
          Type: Api
          Properties:
            Path: /transactions/close/{transactionId}
            Method: put
      Policies:
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          YETI_TRANSACTIONS_TABLE:
            Ref: YetiTransactionsTableName

  YetiTransactionsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName:
        Ref: YetiTransactionsTableName
      AttributeDefinitions:
        - AttributeName: "TransactionId"
          AttributeType: "S"
        - AttributeName: "SenderFirstName"
          AttributeType: "S"
        - AttributeName: "SenderLastName"
          AttributeType: "S"
        - AttributeName: "SenderEmail"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "TransactionId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      GlobalSecondaryIndexes:
        - IndexName: "TransactionsBySenderNameIndex"
          KeySchema:
            - AttributeName: "SenderFirstName"
              KeyType: "HASH"
            - AttributeName: "SenderLastName"
              KeyType: "RANGE"
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: "3"
            WriteCapacityUnits: "3"
        - IndexName: "TransactionsBySenderEmailIndex"
          KeySchema:
            - AttributeName: "SenderEmail"
              KeyType: "HASH"
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: "3"
            WriteCapacityUnits: "3"



