AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  YetiTransactionsTableName:
    Description: The name of the main transactions table
    Type: String
  YetiLoginsTableName:
    Description: The name of the logins information table
    Type: String
  YetiDevicesTableName:
    Description: The name of the devices information table
    Type: String

Resources:
  YetiApiLoadTransactions:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: YetiApi-LoadTransactions
      Handler: src/yeti_api.load_transactions
      Timeout: 10
      Runtime: python3.6
      Events:
        LoadTransactions:
          Type: Api
          Properties:
            Path: /transactions
            Method: get
            RestApiId:
              Ref: ProjectYetiApi
      Policies:
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          YETI_TRANSACTIONS_TABLE:
            Ref: YetiTransactionsTableName
#  YetiApiCloseTransaction:
#    Type: AWS::Serverless::Function
#    Properties:
#      FunctionName: YetiApi-CloseTransaction
#      Handler: src/yeti_api.close_transaction
#      Timeout: 10
#      Runtime: python3.6
#      Events:
#        LoadAllTransactions:
#          Type: Api
#          Properties:
#            Path: /transactions/close/{transactionId}
#            Method: put
#            RestApiId:
#              Ref: ProjectYetiApi
#      Policies:
#        - AmazonDynamoDBFullAccess
#      Environment:
#        Variables:
#          YETI_TRANSACTIONS_TABLE:
#            Ref: YetiTransactionsTableName
  YetiApiLogin:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: YetiApi-Login
      Handler: src/yeti_api.login
      Timeout: 10
      Runtime: python3.6
      Events:
        LoadAllTransactions:
          Type: Api
          Properties:
            Path: /user/login
            Method: post
            RestApiId:
              Ref: ProjectYetiApi
      Policies:
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          YETI_TRANSACTIONS_TABLE:
            Ref: YetiTransactionsTableName
          YETI_LOGINS_TABLE:
            Ref: YetiLoginsTableName
          YETI_DEVICES_TABLE:
            Ref: YetiDevicesTableName

  YetiTransactionsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName:
        Ref: YetiTransactionsTableName
      AttributeDefinitions:
        - AttributeName: "TransactionId"
          AttributeType: "S"
        - AttributeName: "SenderFirstName"
          AttributeType: "S"
        - AttributeName: "SenderLastName"
          AttributeType: "S"
        - AttributeName: "SenderEmail"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "TransactionId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      GlobalSecondaryIndexes:
        - IndexName: "TransactionsBySenderNameIndex"
          KeySchema:
            - AttributeName: "SenderFirstName"
              KeyType: "HASH"
            - AttributeName: "SenderLastName"
              KeyType: "RANGE"
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: "3"
            WriteCapacityUnits: "3"
        - IndexName: "TransactionsBySenderEmailIndex"
          KeySchema:
            - AttributeName: "SenderEmail"
              KeyType: "HASH"
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: "3"
            WriteCapacityUnits: "3"
  YetiLoginsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName:
        Ref: YetiLoginsTableName
      AttributeDefinitions:
        - AttributeName: "Email"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "Email"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
  YetiDevicesTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName:
        Ref: YetiDevicesTableName
      AttributeDefinitions:
        - AttributeName: "DeviceId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "DeviceId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  # API Gateway
  ProjectYetiApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: ProjecYetiApi
      StageName: prod
      DefinitionUri: swagger.yml
